# Generated by Django 2.1 on 2019-09-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_description',
            field=models.TextField(blank=True, null=True, verbose_name='Category Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=100, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/post_img'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='your_cv',
            field=models.FileField(blank=True, null=True, upload_to='uploads/pdf'),
        ),
    ]
