# Generated by Django 2.1.7 on 2019-09-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='About Image')),
                ('about_desc', models.TextField(verbose_name='About Description')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=100)),
                ('service_desc', models.TextField(verbose_name='Service Description')),
            ],
        ),
    ]
