# Generated by Django 2.1.7 on 2019-09-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('referer', models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('nairaland', 'Nairaland'), ('instagram', 'Instagram'), ('', 'Please Choose')], default='', max_length=30, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
